### ISSUE TITLE
[Bug]: Unknown parameters

### ISSUE THREAD

**Issue by matteo1313** [epi2me-labs/wf-alignment#13]
### What happened?

![Screenshot from 2023-03-15 11-38-25](https://user-images.githubusercontent.com/81880944/225413696-3b39741e-e308-42ba-83bd-9d7f4dda06b5.png)

Hello,

Thank you for creating this great program. It used to work perfectly now I am getting errors that the input parameters are not correct. Any advice on how to fix this?

### Operating System

ubuntu 20.04

### Workflow Execution

Command line

### Workflow Execution - CLI Execution Profile

None

### Workflow Version

0.2.0

### Relevant log output

```shell
Please see above screenshot
```

**Comment by sarahjeeeze** [comment]
Hi, your input `--fastq` parameter looks like it has a space in it and a backslash

**Comment by julibeg** [comment]
Hi @matteo1313!

Hmm, could it be that your command was ill-formatted somehow? My first guess is that there might have been an unwanted whitespace after the backslash on the first line. Therefore, the newline character at the end of the first line wasn't escaped and you actually ran two commands instead of just one. This would match with the parameter check failing (since you'd have essentially run `nextflow run epi2me-labs/wf-alignment -r v0.2.0` with no extra params) and the shell complaining about `--fastq` being unknown (since your second command would have been `--fastq ...`).

These assumptions could also be wrong of course; so please let us know If the problem persists!

Also, can I ask why you are running v0.2.0 and not a current version of the workflow? Thanks!

**Comment by julibeg** [comment]
Closing as there was no more response.
