### ISSUE TITLE
EPI2ME running error

### ISSUE THREAD

**Issue by lshi238** [epi2me-labs/wf-alignment#23]
### Operating System

Windows 10

### Workflow Version

v1.0.2

### Workflow Execution

EPI2ME Desktop application

### EPI2ME Version

v5.1.8

### Workflow Execution - CLI Execution Profile

None

### What happened?

I am running EPI2ME on Windows, but it stopped with errors. I also run the demo data, which didn't work, either. Please find the error logs attached.
[EPI2ME_issue_export.tar.gz](https://github.com/epi2me-labs/wf-alignment/files/13923129/EPI2ME_issue_export.tar.gz)
[EPI2ME_issue_export.tar-demodata.gz](https://github.com/epi2me-labs/wf-alignment/files/13923130/EPI2ME_issue_export.tar-demodata.gz)

### Relevant log output

```shell
Please find the attached files above.
```

**Comment by julibeg** [comment]
Hi @lshi238,

From the logs it looks like this is caused by connectivity issues.

In the the demo data logs, for example, the app wasn't able to download the demo dataset using `curl`.
```
2024-01-11T21:02Z │ 01HKX59SEBRAWT4JC6T9KXTHXS │ RUNNING   │ Launch demo          │ Downloading demo data
2024-01-11T21:13Z │ 01HKX59SEBRAWT4JC6T9KXTHXS │ FAILED    │ Launch demo          │ Error running cURL
```

And when running with your own data, Docker failed to pull a layer of the required image
```
Command error:
  edaedc954fb5: Retrying in 3 seconds
  edaedc954fb5: Retrying in 2 seconds
  edaedc954fb5: Retrying in 1 second
...
```

Given that the workflow was successfully installed earlier, the app was able to reach the internet at some point. Thus, my best guess is that either your connection was shaky when you tried running the workflow or that your networking / firewall setup is such that it permits traffic for some connections (e.g. for pulling a workflow from github), but not for others.

In the first case the problem should be transient. Could you please re-open the app (or reboot your machine), try again, and let us know if it worked then?

Thanks

**Comment by julibeg** [comment]
Closing as there was no response
